# Generated by Django 5.2.4 on 2025-08-05 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='closing_time_weekday',
            new_name='closing_time_mon_to_thu',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='closing_time_weekend',
            new_name='closing_time_sunday',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='opening_time_weekday',
            new_name='opening_time_friday',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='opening_time_weekend',
            new_name='opening_time_sunday',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='animation_day',
            field=models.CharField(blank=True, help_text='Jour des animations (ex: Mardi)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='animations_enabled',
            field=models.BooleanField(default=False, help_text='Animations/conférences disponibles'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closing_time_friday',
            field=models.TimeField(default=datetime.time(1, 0)),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closing_time_saturday',
            field=models.TimeField(default=datetime.time(5, 0)),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_trays_available',
            field=models.BooleanField(default=False, help_text='Plateaux repas livrables'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='member_trays_available',
            field=models.BooleanField(default=False, help_text='Plateaux membres'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_time_mon_to_thu',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_time_saturday',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Nombre total de places assises'),
        ),
    ]
