# Generated by Django 5.2.5 on 2025-08-08 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_evenement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de places (optionnel)', null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='is_blocking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evenement',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public ou sur invitation'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Si non null, évènement dans cette salle', null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.room'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='rrule',
            field=models.CharField(blank=True, help_text='RRULE iCal ex: FREQ=WEEKLY;BYDAY=TU', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('FULL', 'Complet'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='EvenementRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='restaurants.evenement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
