# Generated by Django 5.2.5 on 2025-08-29 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_eventinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('restaurant', 'date')},
            },
        ),
    ]
