# Generated by Django 5.2.5 on 2025-09-09 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_evenement_cancelled_at_evenement_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evenement',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterField(
            model_name='evenement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['restaurant', 'date'], name='restaurants_restaur_2e3fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['status'], name='restaurants_status_307a2d_idx'),
        ),
    ]
