# Generated by Django 5.2.6 on 2025-09-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_alter_evenement_options_alter_evenement_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='requires_supplier_confirmation',
            field=models.BooleanField(default=False, help_text="Si vrai, les invitations 'producteurs' doivent être acceptées avant une date limite."),
        ),
        migrations.AddField(
            model_name='evenement',
            name='supplier_deadline_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Nombre de jours avant la date de l’événement : deadline d’acceptation producteurs.'),
        ),
        migrations.AddField(
            model_name='eventinvite',
            name='invitee_role',
            field=models.CharField(choices=[('ANY', 'Générique'), ('SUPPLIER', 'Producteur / Fournisseur')], default='ANY', max_length=16),
        ),
        migrations.AddIndex(
            model_name='eventinvite',
            index=models.Index(fields=['event', 'invitee_role'], name='restaurants_event_i_881b13_idx'),
        ),
    ]
