# Generated by Django 5.2.6 on 2025-09-24 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_evenement_requires_supplier_confirmation_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventinvite',
            name='restaurants_event_i_881b13_idx',
        ),
        migrations.RemoveField(
            model_name='eventinvite',
            name='invitee_role',
        ),
        migrations.AddField(
            model_name='reservation',
            name='party_size',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de couverts demandés'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evenement',
            name='supplier_deadline_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Nombre de jours avant la date de l’événement : date limite d’acceptation pour les producteurs.'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='full_restaurant',
            field=models.BooleanField(default=False, help_text='Réservation de tout le restaurant (décision resto)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reservations',
                to='restaurants.restaurant',
                null=True,
            ),
        ),
    ]
