# Generated by Django 5.2.7 on 2025-10-03 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_fix_reservation_party_and_restaurant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinvite',
            name='invited_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'FOURNISSEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventinvite',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('REVOKED', 'Révoquée'), ('DECLINED', 'Refusée')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='eventinvite',
            index=models.Index(fields=['invited_user', 'status'], name='restaurants_invited_822947_idx'),
        ),
    ]
