# Generated by Django 5.2.7 on 2025-10-08 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_offercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieroffer',
            name='min_order_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Quantité minimale (optionnel).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
