# Generated by Django 5.2.5 on 2025-09-09 09:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default="Veg'N Bio Rewards", max_length=120)),
                ('description', models.TextField(blank=True)),
                ('earn_rate_per_euro', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('redeem_rate_euro_per_point', models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=6)),
                ('rules', models.TextField(blank=True, help_text='Règles, seuils, bonus (texte libre).')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('points_balance', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EARN', 'Earn'), ('SPEND', 'Spend'), ('ADJUST', 'Adjust')], max_length=10)),
                ('points', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('related_order_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fidelite.membership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
