# Generated by Django 5.2.5 on 2025-08-10 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0009_eventinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('restaurants', models.ManyToManyField(related_name='menus', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_bio', models.BooleanField(default=True)),
                ('producer_name', models.CharField(blank=True, max_length=120, null=True)),
                ('region', models.CharField(default='Île-de-France', max_length=120)),
                ('is_vegetarian', models.BooleanField(default=True)),
                ('allergens', models.ManyToManyField(blank=True, related_name='products', to='menu.allergen')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_allergens', models.ManyToManyField(blank=True, related_name='dishes_extra', to='menu.allergen')),
                ('products', models.ManyToManyField(blank=True, related_name='dishes', to='menu.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DishAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='menu.dish')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_availabilities', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('dish', 'restaurant', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('ENTREE', 'Entrée'), ('PLAT', 'Plat'), ('DESSERT', 'Dessert'), ('BOISSON', 'Boisson')], max_length=16)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.dish')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu')),
            ],
            options={
                'ordering': ['menu', 'course_type'],
                'unique_together': {('menu', 'dish', 'course_type')},
            },
        ),
    ]
