# Generated by Django 5.2.6 on 2025-09-24 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
        ('restaurants', '0014_remove_eventinvite_restaurants_event_i_881b13_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryslot',
            options={'ordering': ['restaurant', 'start']},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='menu.dish'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecom_cart_items', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='deliveryslot',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecom_delivery_slots', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecom_orders', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('DELIVERY', 'Livraison'), ('TAKEAWAY', 'À emporter'), ('DINE_IN', 'Sur place')], default='DELIVERY', max_length=16),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.dish'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecom_order_items', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='external_item_id',
            field=models.CharField(help_text="ID du plat/produit dans un autre service ou l'ID du Dish", max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.deliveryslot'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'restaurant', 'external_item_id')},
        ),
    ]
