# Generated by Django 5.2.6 on 2025-09-26 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96)),
                ('aliases', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('references', models.JSONField(blank=True, default=list)),
                ('prevalence', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField(blank=True)),
                ('extracted_symptoms', models.JSONField(blank=True, default=list)),
                ('symptom_codes', models.JSONField(blank=True, default=list)),
                ('triage', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('differential', models.JSONField(blank=True, default=list)),
                ('advice', models.TextField(blank=True)),
                ('model_trace', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='vetbot.breed')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseRedFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_flags', to='vetbot.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useful', models.BooleanField(blank=True, null=True)),
                ('validated_diagnosis', models.CharField(blank=True, max_length=128)),
                ('by_vet', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='vetbot.case')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Species',
                'indexes': [models.Index(fields=['code'], name='vetbot_spec_code_94e5d9_idx')],
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='vetbot.species'),
        ),
        migrations.AddField(
            model_name='case',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='vetbot.species'),
        ),
        migrations.AddField(
            model_name='breed',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='vetbot.species'),
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('snomed_id', models.CharField(blank=True, max_length=32)),
                ('venom_code', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='vetbot_symp_code_10f212_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiseaseSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('critical', models.BooleanField(default=False)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_links', to='vetbot.disease')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_links', to='vetbot.symptom')),
            ],
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['species', 'code'], name='vetbot_dise_species_6d3a63_idx'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['species', 'name'], name='vetbot_dise_species_c96c17_idx'),
        ),
        migrations.AddIndex(
            model_name='breed',
            index=models.Index(fields=['species', 'name'], name='vetbot_bree_species_0b1166_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together={('species', 'name')},
        ),
        migrations.AddIndex(
            model_name='diseasesymptom',
            index=models.Index(fields=['disease', 'symptom'], name='vetbot_dise_disease_77071a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diseasesymptom',
            unique_together={('disease', 'symptom')},
        ),
    ]
