# Generated by Django 5.2.4 on 2025-09-16 13:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_symptoms', models.JSONField(default=list)),
                ('predictions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vetbot.breed')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vetbot.species')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_useful', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chosen_diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vetbot.disease')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='vetbot.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='ReportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='mobile', max_length=16)),
                ('event_type', models.CharField(choices=[('functional', 'Functional'), ('technical', 'Technical')], max_length=16)),
                ('category', models.CharField(choices=[('missing_symptom', 'Missing Symptom'), ('not_useful', 'Not Useful'), ('underestimated_urgency', 'Underestimated Urgency'), ('bug_ui', 'UI Bug'), ('http_error', 'HTTP Error'), ('timeout', 'Timeout'), ('other', 'Other')], max_length=32)),
                ('message', models.CharField(blank=True, max_length=512)),
                ('context_json', models.JSONField(blank=True, default=dict)),
                ('endpoint', models.CharField(blank=True, max_length=256)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vetbot.consultation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='species',
            field=models.ManyToManyField(blank=True, related_name='diseases', to='vetbot.species'),
        ),
        migrations.AddField(
            model_name='breed',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='vetbot.species'),
        ),
        migrations.CreateModel(
            name='DiseaseBreedRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_risks', to='vetbot.breed')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed_risks', to='vetbot.disease')),
            ],
            options={
                'unique_together': {('disease', 'breed')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together={('species', 'name')},
        ),
        migrations.CreateModel(
            name='DiseaseSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('MUST', 'Must Have'), ('NICE', 'Nice To Have')], max_length=4)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_symptoms', to='vetbot.disease')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetbot.symptom')),
            ],
            options={
                'unique_together': {('disease', 'symptom', 'kind')},
            },
        ),
    ]
