# Generated by Django 5.2.6 on 2025-09-18 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetbot', '0003_add_case_to_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='vetbot.species'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='vetbot.case'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['species', 'code'], name='vetbot_dise_species_6d3a63_idx'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['species', 'name'], name='vetbot_dise_species_c96c17_idx'),
        ),
    ]
