# Generated by Django 5.2.6 on 2025-09-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetbot', '0009_schema_alignment_guardrail'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='disease',
            new_name='vetbot_dise_species_6d3a63_idx',
            old_name='vetbot_dise_species_code_idx',
        ),
        migrations.RenameIndex(
            model_name='disease',
            new_name='vetbot_dise_species_c96c17_idx',
            old_name='vetbot_dise_species_name_idx',
        ),
        migrations.AlterField(
            model_name='symptom',
            name='snomed_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='venom_code',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
